/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HiddenMultisigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeOwnerCount"
      | "approve"
      | "confidentialProtocolId"
      | "finalizeExecute"
      | "getProposal"
      | "getReadyHandle"
      | "initialize"
      | "initialized"
      | "isActive"
      | "nextPropId"
      | "ownersLength"
      | "proposeAddSigner"
      | "proposeRemoveSigner"
      | "proposeSetThreshold"
      | "proposeTransfer"
      | "relayer"
      | "requestExecute"
      | "threshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approved"
      | "Deposit"
      | "Executed"
      | "ExecutionRequested"
      | "Initialized"
      | "ProposalCreated"
      | "PublicDecryptionVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeOwnerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeExecute",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReadyHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike[], BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPropId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownersLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeAddSigner",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeRemoveSigner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeSetThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTransfer",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestExecute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "activeOwnerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReadyHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextPropId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownersLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeAddSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeRemoveSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeSetThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
}

export namespace ApprovedEvent {
  export type InputTuple = [propId: BigNumberish, attempts: BigNumberish];
  export type OutputTuple = [propId: bigint, attempts: bigint];
  export interface OutputObject {
    propId: bigint;
    attempts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [from: AddressLike, value: BigNumberish];
  export type OutputTuple = [from: string, value: bigint];
  export interface OutputObject {
    from: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    propId: BigNumberish,
    ptype: BigNumberish,
    ready: boolean
  ];
  export type OutputTuple = [propId: bigint, ptype: bigint, ready: boolean];
  export interface OutputObject {
    propId: bigint;
    ptype: bigint;
    ready: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionRequestedEvent {
  export type InputTuple = [propId: BigNumberish, readyHandle: BytesLike];
  export type OutputTuple = [propId: bigint, readyHandle: string];
  export interface OutputObject {
    propId: bigint;
    readyHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [threshold: BigNumberish, ownersCount: BigNumberish];
  export type OutputTuple = [threshold: bigint, ownersCount: bigint];
  export interface OutputObject {
    threshold: bigint;
    ownersCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [propId: BigNumberish, ptype: BigNumberish];
  export type OutputTuple = [propId: bigint, ptype: bigint];
  export interface OutputObject {
    propId: bigint;
    ptype: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HiddenMultisig extends BaseContract {
  connect(runner?: ContractRunner | null): HiddenMultisig;
  waitForDeployment(): Promise<this>;

  interface: HiddenMultisigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeOwnerCount: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [propId: BigNumberish, encSigner: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  finalizeExecute: TypedContractMethod<
    [
      propId: BigNumberish,
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getProposal: TypedContractMethod<
    [propId: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean, boolean, bigint] & {
        ptype: bigint;
        data: string;
        approvalAttempts: bigint;
        decryptionPending: boolean;
        executed: boolean;
        ready: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getReadyHandle: TypedContractMethod<[propId: BigNumberish], [string], "view">;

  initialize: TypedContractMethod<
    [encOwners: BytesLike[], proof: BytesLike, _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  isActive: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  nextPropId: TypedContractMethod<[], [bigint], "view">;

  ownersLength: TypedContractMethod<[], [bigint], "view">;

  proposeAddSigner: TypedContractMethod<
    [encNewOwner: BytesLike, proof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  proposeRemoveSigner: TypedContractMethod<
    [idx: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proposeSetThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proposeTransfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  requestExecute: TypedContractMethod<
    [propId: BigNumberish],
    [void],
    "nonpayable"
  >;

  threshold: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeOwnerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [propId: BigNumberish, encSigner: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeExecute"
  ): TypedContractMethod<
    [
      propId: BigNumberish,
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [propId: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean, boolean, bigint] & {
        ptype: bigint;
        data: string;
        approvalAttempts: bigint;
        decryptionPending: boolean;
        executed: boolean;
        ready: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReadyHandle"
  ): TypedContractMethod<[propId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [encOwners: BytesLike[], proof: BytesLike, _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextPropId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownersLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeAddSigner"
  ): TypedContractMethod<
    [encNewOwner: BytesLike, proof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeRemoveSigner"
  ): TypedContractMethod<[idx: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeSetThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeTransfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestExecute"
  ): TypedContractMethod<[propId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionRequested"
  ): TypedContractEvent<
    ExecutionRequestedEvent.InputTuple,
    ExecutionRequestedEvent.OutputTuple,
    ExecutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;

  filters: {
    "Approved(uint256,uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Executed(uint256,uint8,bool)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "ExecutionRequested(uint256,bytes32)": TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;
    ExecutionRequested: TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;

    "Initialized(uint8,uint256)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ProposalCreated(uint256,uint8)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
  };
}
